Thymesisflow software library and connections manager
OpenCAPI/ThymesisFlow pull request #1
Opened 2020-09-03 14:00 UTC by mgazz

libthymesisflow is the software library providing configuration capabilities for Thymesisflow.

The main features are:

1. Simple APIs to attach and detach remote memory
2. Agent keeping track of current connections
3. Command line interface to abstract low level implementation details
4. Simple interface to monitor latency and rx/tx bandwidth

More information provided in the README

2020-09-07 16:15 UTC, christian-pinto requested changes

2020-09-07 16:15 UTC, christian-pinto commented on libthymesisflow/README.md
> +```
It is not clear that before starting the unit tests you have to start the `thymesisf-agent`. Please specify or change this behavior.

2020-09-07 16:15 UTC, christian-pinto commented on libthymesisflow/README.md
> +**Note:** use `DEBUG=1` is required for running unittests successfully
Is this true for the mock build too? It looks like it is not needed when building mock libraries.

2020-09-07 16:15 UTC, christian-pinto commented on libthymesisflow/README.md
> +* `latency`: average latency on the channel
Is there a unit of measure for the latency metric? If yes, please specify.

2020-09-07 16:15 UTC, christian-pinto commented on libthymesisflow/cmd/thymesisf-agent.c
> +#include "proto.h"
There is no copyright notice in any of the source files, please add to all files missing it (both .h and .c).

2020-09-07 16:15 UTC, christian-pinto commented on libthymesisflow/src/thymesisflow.c
> +int detach(const uint64_t memory_size) {
I would consider renaming this method to something more descriptive. The name `detach` could be too generic for a code base dealing with attaching and detaching memory.

2020-09-07 16:15 UTC, christian-pinto commented on libthymesisflow/src/thymesisflow.c
> +    if (posix_memalign((void **)&conn->ea, 128, (256 >> 20)) != 0) {
Defining a macro for `128` could help other developers understanding what's that value about.

2020-09-08 08:10 UTC, mgazz commented
Thank you @christian-pinto for the review. These are all valid points. I'll address them and update the pull requests.

2020-09-14 09:53 UTC, christian-pinto approved these changes

2020-09-14 09:54 UTC, merged

2020-09-14 09:54 UTC, christian-pinto commented
All looks good to me. Just merged, thanks!